// flow-typed signature: ba4d11f65d541d5369464fc1c19fffe2
// flow-typed version: <<STUB>>/article-json-react-embeds_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'article-json-react-embeds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'article-json-react-embeds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'article-json-react-embeds/dist/index' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/render-iframe' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/render-text' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/custom' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/facebook' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/image' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/index' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/instagram' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/spotify' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/tidal' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/tumblr' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/twitter' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/video' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/vine' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/dist/types/youtube' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/index' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/render-iframe' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/render-text' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/custom' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/facebook' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/image' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/index' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/instagram' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/spotify' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/tidal' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/tumblr' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/twitter' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/video' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/vine' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/lib/types/youtube' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'article-json-react-embeds/test/index-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'article-json-react-embeds/dist/index.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/index'>;
}
declare module 'article-json-react-embeds/dist/render-iframe.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/render-iframe'>;
}
declare module 'article-json-react-embeds/dist/render-text.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/render-text'>;
}
declare module 'article-json-react-embeds/dist/types/custom.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/custom'>;
}
declare module 'article-json-react-embeds/dist/types/facebook.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/facebook'>;
}
declare module 'article-json-react-embeds/dist/types/image.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/image'>;
}
declare module 'article-json-react-embeds/dist/types/index.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/index'>;
}
declare module 'article-json-react-embeds/dist/types/instagram.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/instagram'>;
}
declare module 'article-json-react-embeds/dist/types/spotify.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/spotify'>;
}
declare module 'article-json-react-embeds/dist/types/tidal.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/tidal'>;
}
declare module 'article-json-react-embeds/dist/types/tumblr.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/tumblr'>;
}
declare module 'article-json-react-embeds/dist/types/twitter.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/twitter'>;
}
declare module 'article-json-react-embeds/dist/types/video.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/video'>;
}
declare module 'article-json-react-embeds/dist/types/vine.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/vine'>;
}
declare module 'article-json-react-embeds/dist/types/youtube.js' {
  declare module.exports: $Exports<'article-json-react-embeds/dist/types/youtube'>;
}
declare module 'article-json-react-embeds/lib/index.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/index'>;
}
declare module 'article-json-react-embeds/lib/render-iframe.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/render-iframe'>;
}
declare module 'article-json-react-embeds/lib/render-text.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/render-text'>;
}
declare module 'article-json-react-embeds/lib/types/custom.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/custom'>;
}
declare module 'article-json-react-embeds/lib/types/facebook.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/facebook'>;
}
declare module 'article-json-react-embeds/lib/types/image.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/image'>;
}
declare module 'article-json-react-embeds/lib/types/index.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/index'>;
}
declare module 'article-json-react-embeds/lib/types/instagram.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/instagram'>;
}
declare module 'article-json-react-embeds/lib/types/spotify.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/spotify'>;
}
declare module 'article-json-react-embeds/lib/types/tidal.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/tidal'>;
}
declare module 'article-json-react-embeds/lib/types/tumblr.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/tumblr'>;
}
declare module 'article-json-react-embeds/lib/types/twitter.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/twitter'>;
}
declare module 'article-json-react-embeds/lib/types/video.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/video'>;
}
declare module 'article-json-react-embeds/lib/types/vine.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/vine'>;
}
declare module 'article-json-react-embeds/lib/types/youtube.js' {
  declare module.exports: $Exports<'article-json-react-embeds/lib/types/youtube'>;
}
declare module 'article-json-react-embeds/test/fixtures/index.js' {
  declare module.exports: $Exports<'article-json-react-embeds/test/fixtures/index'>;
}
declare module 'article-json-react-embeds/test/index-test.js' {
  declare module.exports: $Exports<'article-json-react-embeds/test/index-test'>;
}
