// flow-typed signature: 8f3b58e207a69d469ac9634927af7eba
// flow-typed version: <<STUB>>/article-json-react-render_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'article-json-react-render'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'article-json-react-render' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'article-json-react-render/dist/block-list' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/components/article' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/components/blockquote' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/components/embed' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/components/header' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/components/paragraph' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/index' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/render-text' {
  declare module.exports: any;
}

declare module 'article-json-react-render/dist/types' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/babel-plugin-transform-object-assign_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/babel-tape-runner_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/enzyme_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/flow-bin_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/lodash.startswith_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/miclint_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/nyc_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/react-addons-test-utils_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/snazzy_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/flow-typed/npm/tapava_vx.x.x' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/block-list' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/components/article' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/components/blockquote' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/components/embed' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/components/header' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/components/paragraph' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/index' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/render-text' {
  declare module.exports: any;
}

declare module 'article-json-react-render/lib/types' {
  declare module.exports: any;
}

declare module 'article-json-react-render/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'article-json-react-render/dist/block-list.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/block-list'>;
}
declare module 'article-json-react-render/dist/components/article.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/components/article'>;
}
declare module 'article-json-react-render/dist/components/blockquote.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/components/blockquote'>;
}
declare module 'article-json-react-render/dist/components/embed.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/components/embed'>;
}
declare module 'article-json-react-render/dist/components/header.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/components/header'>;
}
declare module 'article-json-react-render/dist/components/paragraph.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/components/paragraph'>;
}
declare module 'article-json-react-render/dist/index.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/index'>;
}
declare module 'article-json-react-render/dist/render-text.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/render-text'>;
}
declare module 'article-json-react-render/dist/types.js' {
  declare module.exports: $Exports<'article-json-react-render/dist/types'>;
}
declare module 'article-json-react-render/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/babel-plugin-transform-object-assign_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/babel-plugin-transform-object-assign_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/babel-plugin-transform-react-jsx_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/babel-tape-runner_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/babel-tape-runner_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/enzyme_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/enzyme_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/flow-bin_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/flow-bin_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/lodash.startswith_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/lodash.startswith_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/miclint_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/miclint_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/nyc_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/nyc_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/react-addons-test-utils_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/react-addons-test-utils_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/snazzy_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/snazzy_vx.x.x'>;
}
declare module 'article-json-react-render/flow-typed/npm/tapava_vx.x.x.js' {
  declare module.exports: $Exports<'article-json-react-render/flow-typed/npm/tapava_vx.x.x'>;
}
declare module 'article-json-react-render/lib/block-list.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/block-list'>;
}
declare module 'article-json-react-render/lib/components/article.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/components/article'>;
}
declare module 'article-json-react-render/lib/components/blockquote.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/components/blockquote'>;
}
declare module 'article-json-react-render/lib/components/embed.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/components/embed'>;
}
declare module 'article-json-react-render/lib/components/header.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/components/header'>;
}
declare module 'article-json-react-render/lib/components/paragraph.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/components/paragraph'>;
}
declare module 'article-json-react-render/lib/index.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/index'>;
}
declare module 'article-json-react-render/lib/render-text.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/render-text'>;
}
declare module 'article-json-react-render/lib/types.js' {
  declare module.exports: $Exports<'article-json-react-render/lib/types'>;
}
declare module 'article-json-react-render/test.js' {
  declare module.exports: $Exports<'article-json-react-render/test'>;
}
