// flow-typed signature: 1db50900cbc179f5a50f7bfc63dec4e3
// flow-typed version: <<STUB>>/beefy_v^2.1.6/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'beefy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'beefy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'beefy/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'beefy/lib/accumulate-error' {
  declare module.exports: any;
}

declare module 'beefy/lib/args-to-options' {
  declare module.exports: any;
}

declare module 'beefy/lib/bundlers/browserify' {
  declare module.exports: any;
}

declare module 'beefy/lib/bundlers/watchify' {
  declare module.exports: any;
}

declare module 'beefy/lib/cli' {
  declare module.exports: any;
}

declare module 'beefy/lib/create-handler' {
  declare module.exports: any;
}

declare module 'beefy/lib/extract-port' {
  declare module.exports: any;
}

declare module 'beefy/lib/frontend-js/error' {
  declare module.exports: any;
}

declare module 'beefy/lib/frontend-js/live-reload' {
  declare module.exports: any;
}

declare module 'beefy/lib/handlers/bundle' {
  declare module.exports: any;
}

declare module 'beefy/lib/handlers/default-index' {
  declare module.exports: any;
}

declare module 'beefy/lib/handlers/legacy-bundle' {
  declare module.exports: any;
}

declare module 'beefy/lib/handlers/live-reload' {
  declare module.exports: any;
}

declare module 'beefy/lib/handlers/log' {
  declare module.exports: any;
}

declare module 'beefy/lib/handlers/static' {
  declare module.exports: any;
}

declare module 'beefy/lib/help' {
  declare module.exports: any;
}

declare module 'beefy/lib/make-io' {
  declare module.exports: any;
}

declare module 'beefy/lib/normalize-entry-points' {
  declare module.exports: any;
}

declare module 'beefy/lib/setup-bundlers' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/bad-transform' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/browserify/bin/args' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/browserify/index' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/example-project/bad-file' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/example-project/file-1' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/example-project/file-2' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/multi-bundle/a' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/multi-bundle/b' {
  declare module.exports: any;
}

declare module 'beefy/test/fixtures/multi-bundle/c' {
  declare module.exports: any;
}

declare module 'beefy/test/http-server' {
  declare module.exports: any;
}

declare module 'beefy/test/index' {
  declare module.exports: any;
}

declare module 'beefy/test/stub-fs-watch' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/args-to-options' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/bundler-browserify' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/bundler-watchify' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/cli' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/create-handler' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/extract-port' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/handler-bundle' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/handler-default-index' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/handler-legacy-bundle' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/handler-log' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/handler-static' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/help' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/integration' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/lint' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/normalize-entry-points' {
  declare module.exports: any;
}

declare module 'beefy/test/tests/setup-bundlers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'beefy/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'beefy/coverage/lcov-report/prettify'>;
}
declare module 'beefy/index' {
  declare module.exports: $Exports<'beefy'>;
}
declare module 'beefy/index.js' {
  declare module.exports: $Exports<'beefy'>;
}
declare module 'beefy/lib/accumulate-error.js' {
  declare module.exports: $Exports<'beefy/lib/accumulate-error'>;
}
declare module 'beefy/lib/args-to-options.js' {
  declare module.exports: $Exports<'beefy/lib/args-to-options'>;
}
declare module 'beefy/lib/bundlers/browserify.js' {
  declare module.exports: $Exports<'beefy/lib/bundlers/browserify'>;
}
declare module 'beefy/lib/bundlers/watchify.js' {
  declare module.exports: $Exports<'beefy/lib/bundlers/watchify'>;
}
declare module 'beefy/lib/cli.js' {
  declare module.exports: $Exports<'beefy/lib/cli'>;
}
declare module 'beefy/lib/create-handler.js' {
  declare module.exports: $Exports<'beefy/lib/create-handler'>;
}
declare module 'beefy/lib/extract-port.js' {
  declare module.exports: $Exports<'beefy/lib/extract-port'>;
}
declare module 'beefy/lib/frontend-js/error.js' {
  declare module.exports: $Exports<'beefy/lib/frontend-js/error'>;
}
declare module 'beefy/lib/frontend-js/live-reload.js' {
  declare module.exports: $Exports<'beefy/lib/frontend-js/live-reload'>;
}
declare module 'beefy/lib/handlers/bundle.js' {
  declare module.exports: $Exports<'beefy/lib/handlers/bundle'>;
}
declare module 'beefy/lib/handlers/default-index.js' {
  declare module.exports: $Exports<'beefy/lib/handlers/default-index'>;
}
declare module 'beefy/lib/handlers/legacy-bundle.js' {
  declare module.exports: $Exports<'beefy/lib/handlers/legacy-bundle'>;
}
declare module 'beefy/lib/handlers/live-reload.js' {
  declare module.exports: $Exports<'beefy/lib/handlers/live-reload'>;
}
declare module 'beefy/lib/handlers/log.js' {
  declare module.exports: $Exports<'beefy/lib/handlers/log'>;
}
declare module 'beefy/lib/handlers/static.js' {
  declare module.exports: $Exports<'beefy/lib/handlers/static'>;
}
declare module 'beefy/lib/help.js' {
  declare module.exports: $Exports<'beefy/lib/help'>;
}
declare module 'beefy/lib/make-io.js' {
  declare module.exports: $Exports<'beefy/lib/make-io'>;
}
declare module 'beefy/lib/normalize-entry-points.js' {
  declare module.exports: $Exports<'beefy/lib/normalize-entry-points'>;
}
declare module 'beefy/lib/setup-bundlers.js' {
  declare module.exports: $Exports<'beefy/lib/setup-bundlers'>;
}
declare module 'beefy/test/fixtures/bad-transform.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/bad-transform'>;
}
declare module 'beefy/test/fixtures/browserify/bin/args.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/browserify/bin/args'>;
}
declare module 'beefy/test/fixtures/browserify/index.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/browserify/index'>;
}
declare module 'beefy/test/fixtures/example-project/bad-file.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/example-project/bad-file'>;
}
declare module 'beefy/test/fixtures/example-project/file-1.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/example-project/file-1'>;
}
declare module 'beefy/test/fixtures/example-project/file-2.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/example-project/file-2'>;
}
declare module 'beefy/test/fixtures/multi-bundle/a.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/multi-bundle/a'>;
}
declare module 'beefy/test/fixtures/multi-bundle/b.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/multi-bundle/b'>;
}
declare module 'beefy/test/fixtures/multi-bundle/c.js' {
  declare module.exports: $Exports<'beefy/test/fixtures/multi-bundle/c'>;
}
declare module 'beefy/test/http-server.js' {
  declare module.exports: $Exports<'beefy/test/http-server'>;
}
declare module 'beefy/test/index.js' {
  declare module.exports: $Exports<'beefy/test/index'>;
}
declare module 'beefy/test/stub-fs-watch.js' {
  declare module.exports: $Exports<'beefy/test/stub-fs-watch'>;
}
declare module 'beefy/test/tests/args-to-options.js' {
  declare module.exports: $Exports<'beefy/test/tests/args-to-options'>;
}
declare module 'beefy/test/tests/bundler-browserify.js' {
  declare module.exports: $Exports<'beefy/test/tests/bundler-browserify'>;
}
declare module 'beefy/test/tests/bundler-watchify.js' {
  declare module.exports: $Exports<'beefy/test/tests/bundler-watchify'>;
}
declare module 'beefy/test/tests/cli.js' {
  declare module.exports: $Exports<'beefy/test/tests/cli'>;
}
declare module 'beefy/test/tests/create-handler.js' {
  declare module.exports: $Exports<'beefy/test/tests/create-handler'>;
}
declare module 'beefy/test/tests/extract-port.js' {
  declare module.exports: $Exports<'beefy/test/tests/extract-port'>;
}
declare module 'beefy/test/tests/handler-bundle.js' {
  declare module.exports: $Exports<'beefy/test/tests/handler-bundle'>;
}
declare module 'beefy/test/tests/handler-default-index.js' {
  declare module.exports: $Exports<'beefy/test/tests/handler-default-index'>;
}
declare module 'beefy/test/tests/handler-legacy-bundle.js' {
  declare module.exports: $Exports<'beefy/test/tests/handler-legacy-bundle'>;
}
declare module 'beefy/test/tests/handler-log.js' {
  declare module.exports: $Exports<'beefy/test/tests/handler-log'>;
}
declare module 'beefy/test/tests/handler-static.js' {
  declare module.exports: $Exports<'beefy/test/tests/handler-static'>;
}
declare module 'beefy/test/tests/help.js' {
  declare module.exports: $Exports<'beefy/test/tests/help'>;
}
declare module 'beefy/test/tests/integration.js' {
  declare module.exports: $Exports<'beefy/test/tests/integration'>;
}
declare module 'beefy/test/tests/lint.js' {
  declare module.exports: $Exports<'beefy/test/tests/lint'>;
}
declare module 'beefy/test/tests/normalize-entry-points.js' {
  declare module.exports: $Exports<'beefy/test/tests/normalize-entry-points'>;
}
declare module 'beefy/test/tests/setup-bundlers.js' {
  declare module.exports: $Exports<'beefy/test/tests/setup-bundlers'>;
}
