// flow-typed signature: e69eb3d9f6fc6e7b4c5fe0821b670361
// flow-typed version: <<STUB>>/create-event_v^1.0.9/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'create-event'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'create-event' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'create-event/index' {
  declare module.exports: $Exports<'create-event'>;
}
declare module 'create-event/index.js' {
  declare module.exports: $Exports<'create-event'>;
}
