// flow-typed signature: e3f850e2da885f9801734588f7cf1905
// flow-typed version: <<STUB>>/devtool_v^2.3.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'devtool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'devtool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'devtool/bin/index' {
  declare module.exports: any;
}

declare module 'devtool/bin/spawn' {
  declare module.exports: any;
}

declare module 'devtool/lib/browser-globals' {
  declare module.exports: any;
}

declare module 'devtool/lib/console-hook' {
  declare module.exports: any;
}

declare module 'devtool/lib/file-watch' {
  declare module.exports: any;
}

declare module 'devtool/lib/main-window' {
  declare module.exports: any;
}

declare module 'devtool/lib/parse-args' {
  declare module.exports: any;
}

declare module 'devtool/lib/preload' {
  declare module.exports: any;
}

declare module 'devtool/lib/require-hook' {
  declare module.exports: any;
}

declare module 'devtool/lib/timer-hook' {
  declare module.exports: any;
}

declare module 'devtool/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'devtool/bin/index.js' {
  declare module.exports: $Exports<'devtool/bin/index'>;
}
declare module 'devtool/bin/spawn.js' {
  declare module.exports: $Exports<'devtool/bin/spawn'>;
}
declare module 'devtool/lib/browser-globals.js' {
  declare module.exports: $Exports<'devtool/lib/browser-globals'>;
}
declare module 'devtool/lib/console-hook.js' {
  declare module.exports: $Exports<'devtool/lib/console-hook'>;
}
declare module 'devtool/lib/file-watch.js' {
  declare module.exports: $Exports<'devtool/lib/file-watch'>;
}
declare module 'devtool/lib/main-window.js' {
  declare module.exports: $Exports<'devtool/lib/main-window'>;
}
declare module 'devtool/lib/parse-args.js' {
  declare module.exports: $Exports<'devtool/lib/parse-args'>;
}
declare module 'devtool/lib/preload.js' {
  declare module.exports: $Exports<'devtool/lib/preload'>;
}
declare module 'devtool/lib/require-hook.js' {
  declare module.exports: $Exports<'devtool/lib/require-hook'>;
}
declare module 'devtool/lib/timer-hook.js' {
  declare module.exports: $Exports<'devtool/lib/timer-hook'>;
}
declare module 'devtool/server.js' {
  declare module.exports: $Exports<'devtool/server'>;
}
