// flow-typed signature: 716f2d0dcded1035f27e2fec9449b363
// flow-typed version: <<STUB>>/dift_v^0.1.12/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dift'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dift' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dift/lib/index' {
  declare module.exports: any;
}

declare module 'dift/src/index' {
  declare module.exports: any;
}

declare module 'dift/test/benchmark' {
  declare module.exports: any;
}

declare module 'dift/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dift/lib/index.js' {
  declare module.exports: $Exports<'dift/lib/index'>;
}
declare module 'dift/src/index.js' {
  declare module.exports: $Exports<'dift/src/index'>;
}
declare module 'dift/test/benchmark.js' {
  declare module.exports: $Exports<'dift/test/benchmark'>;
}
declare module 'dift/test/index.js' {
  declare module.exports: $Exports<'dift/test/index'>;
}
