// flow-typed signature: 76b018785d86efded26241f0a008ccd4
// flow-typed version: <<STUB>>/embeds_v^2.5.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'embeds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'embeds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'embeds/dist/dimensions' {
  declare module.exports: any;
}

declare module 'embeds/dist/index' {
  declare module.exports: any;
}

declare module 'embeds/dist/parse-input' {
  declare module.exports: any;
}

declare module 'embeds/dist/parse-text' {
  declare module.exports: any;
}

declare module 'embeds/dist/parse' {
  declare module.exports: any;
}

declare module 'embeds/dist/render-iframe' {
  declare module.exports: any;
}

declare module 'embeds/dist/render-text' {
  declare module.exports: any;
}

declare module 'embeds/dist/render' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/custom' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/facebook' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/image' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/index' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/instagram/index' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/instagram/parse' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/instagram/render' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/spotify' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/tidal' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/tumblr' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/twitter' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/video' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/vine' {
  declare module.exports: any;
}

declare module 'embeds/dist/types/youtube' {
  declare module.exports: any;
}

declare module 'embeds/lib/dimensions' {
  declare module.exports: any;
}

declare module 'embeds/lib/index' {
  declare module.exports: any;
}

declare module 'embeds/lib/parse-input' {
  declare module.exports: any;
}

declare module 'embeds/lib/parse-text' {
  declare module.exports: any;
}

declare module 'embeds/lib/parse' {
  declare module.exports: any;
}

declare module 'embeds/lib/render-iframe' {
  declare module.exports: any;
}

declare module 'embeds/lib/render-text' {
  declare module.exports: any;
}

declare module 'embeds/lib/render' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/custom' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/facebook' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/image' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/index' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/instagram/index' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/instagram/parse' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/instagram/render' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/spotify' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/tidal' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/tumblr' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/twitter' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/video' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/vine' {
  declare module.exports: any;
}

declare module 'embeds/lib/types/youtube' {
  declare module.exports: any;
}

declare module 'embeds/test/embed-code-parse-test' {
  declare module.exports: any;
}

declare module 'embeds/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'embeds/test/html-parse-test' {
  declare module.exports: any;
}

declare module 'embeds/test/hyperscript-compability-test' {
  declare module.exports: any;
}

declare module 'embeds/test/parse-render-test' {
  declare module.exports: any;
}

declare module 'embeds/test/render-test' {
  declare module.exports: any;
}

declare module 'embeds/test/tape-wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'embeds/dist/dimensions.js' {
  declare module.exports: $Exports<'embeds/dist/dimensions'>;
}
declare module 'embeds/dist/index.js' {
  declare module.exports: $Exports<'embeds/dist/index'>;
}
declare module 'embeds/dist/parse-input.js' {
  declare module.exports: $Exports<'embeds/dist/parse-input'>;
}
declare module 'embeds/dist/parse-text.js' {
  declare module.exports: $Exports<'embeds/dist/parse-text'>;
}
declare module 'embeds/dist/parse.js' {
  declare module.exports: $Exports<'embeds/dist/parse'>;
}
declare module 'embeds/dist/render-iframe.js' {
  declare module.exports: $Exports<'embeds/dist/render-iframe'>;
}
declare module 'embeds/dist/render-text.js' {
  declare module.exports: $Exports<'embeds/dist/render-text'>;
}
declare module 'embeds/dist/render.js' {
  declare module.exports: $Exports<'embeds/dist/render'>;
}
declare module 'embeds/dist/types/custom.js' {
  declare module.exports: $Exports<'embeds/dist/types/custom'>;
}
declare module 'embeds/dist/types/facebook.js' {
  declare module.exports: $Exports<'embeds/dist/types/facebook'>;
}
declare module 'embeds/dist/types/image.js' {
  declare module.exports: $Exports<'embeds/dist/types/image'>;
}
declare module 'embeds/dist/types/index.js' {
  declare module.exports: $Exports<'embeds/dist/types/index'>;
}
declare module 'embeds/dist/types/instagram/index.js' {
  declare module.exports: $Exports<'embeds/dist/types/instagram/index'>;
}
declare module 'embeds/dist/types/instagram/parse.js' {
  declare module.exports: $Exports<'embeds/dist/types/instagram/parse'>;
}
declare module 'embeds/dist/types/instagram/render.js' {
  declare module.exports: $Exports<'embeds/dist/types/instagram/render'>;
}
declare module 'embeds/dist/types/spotify.js' {
  declare module.exports: $Exports<'embeds/dist/types/spotify'>;
}
declare module 'embeds/dist/types/tidal.js' {
  declare module.exports: $Exports<'embeds/dist/types/tidal'>;
}
declare module 'embeds/dist/types/tumblr.js' {
  declare module.exports: $Exports<'embeds/dist/types/tumblr'>;
}
declare module 'embeds/dist/types/twitter.js' {
  declare module.exports: $Exports<'embeds/dist/types/twitter'>;
}
declare module 'embeds/dist/types/video.js' {
  declare module.exports: $Exports<'embeds/dist/types/video'>;
}
declare module 'embeds/dist/types/vine.js' {
  declare module.exports: $Exports<'embeds/dist/types/vine'>;
}
declare module 'embeds/dist/types/youtube.js' {
  declare module.exports: $Exports<'embeds/dist/types/youtube'>;
}
declare module 'embeds/lib/dimensions.js' {
  declare module.exports: $Exports<'embeds/lib/dimensions'>;
}
declare module 'embeds/lib/index.js' {
  declare module.exports: $Exports<'embeds/lib/index'>;
}
declare module 'embeds/lib/parse-input.js' {
  declare module.exports: $Exports<'embeds/lib/parse-input'>;
}
declare module 'embeds/lib/parse-text.js' {
  declare module.exports: $Exports<'embeds/lib/parse-text'>;
}
declare module 'embeds/lib/parse.js' {
  declare module.exports: $Exports<'embeds/lib/parse'>;
}
declare module 'embeds/lib/render-iframe.js' {
  declare module.exports: $Exports<'embeds/lib/render-iframe'>;
}
declare module 'embeds/lib/render-text.js' {
  declare module.exports: $Exports<'embeds/lib/render-text'>;
}
declare module 'embeds/lib/render.js' {
  declare module.exports: $Exports<'embeds/lib/render'>;
}
declare module 'embeds/lib/types/custom.js' {
  declare module.exports: $Exports<'embeds/lib/types/custom'>;
}
declare module 'embeds/lib/types/facebook.js' {
  declare module.exports: $Exports<'embeds/lib/types/facebook'>;
}
declare module 'embeds/lib/types/image.js' {
  declare module.exports: $Exports<'embeds/lib/types/image'>;
}
declare module 'embeds/lib/types/index.js' {
  declare module.exports: $Exports<'embeds/lib/types/index'>;
}
declare module 'embeds/lib/types/instagram/index.js' {
  declare module.exports: $Exports<'embeds/lib/types/instagram/index'>;
}
declare module 'embeds/lib/types/instagram/parse.js' {
  declare module.exports: $Exports<'embeds/lib/types/instagram/parse'>;
}
declare module 'embeds/lib/types/instagram/render.js' {
  declare module.exports: $Exports<'embeds/lib/types/instagram/render'>;
}
declare module 'embeds/lib/types/spotify.js' {
  declare module.exports: $Exports<'embeds/lib/types/spotify'>;
}
declare module 'embeds/lib/types/tidal.js' {
  declare module.exports: $Exports<'embeds/lib/types/tidal'>;
}
declare module 'embeds/lib/types/tumblr.js' {
  declare module.exports: $Exports<'embeds/lib/types/tumblr'>;
}
declare module 'embeds/lib/types/twitter.js' {
  declare module.exports: $Exports<'embeds/lib/types/twitter'>;
}
declare module 'embeds/lib/types/video.js' {
  declare module.exports: $Exports<'embeds/lib/types/video'>;
}
declare module 'embeds/lib/types/vine.js' {
  declare module.exports: $Exports<'embeds/lib/types/vine'>;
}
declare module 'embeds/lib/types/youtube.js' {
  declare module.exports: $Exports<'embeds/lib/types/youtube'>;
}
declare module 'embeds/test/embed-code-parse-test.js' {
  declare module.exports: $Exports<'embeds/test/embed-code-parse-test'>;
}
declare module 'embeds/test/fixtures/index.js' {
  declare module.exports: $Exports<'embeds/test/fixtures/index'>;
}
declare module 'embeds/test/html-parse-test.js' {
  declare module.exports: $Exports<'embeds/test/html-parse-test'>;
}
declare module 'embeds/test/hyperscript-compability-test.js' {
  declare module.exports: $Exports<'embeds/test/hyperscript-compability-test'>;
}
declare module 'embeds/test/parse-render-test.js' {
  declare module.exports: $Exports<'embeds/test/parse-render-test'>;
}
declare module 'embeds/test/render-test.js' {
  declare module.exports: $Exports<'embeds/test/render-test'>;
}
declare module 'embeds/test/tape-wrapper.js' {
  declare module.exports: $Exports<'embeds/test/tape-wrapper'>;
}
