// flow-typed signature: e1b9ff53cd6058cd4f513b18f557d705
// flow-typed version: <<STUB>>/get-selection-range-from-elm_v^2.0.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'get-selection-range-from-elm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'get-selection-range-from-elm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'get-selection-range-from-elm/dist/index' {
  declare module.exports: any;
}

declare module 'get-selection-range-from-elm/example' {
  declare module.exports: any;
}

declare module 'get-selection-range-from-elm/lib/index' {
  declare module.exports: any;
}

declare module 'get-selection-range-from-elm/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'get-selection-range-from-elm/dist/index.js' {
  declare module.exports: $Exports<'get-selection-range-from-elm/dist/index'>;
}
declare module 'get-selection-range-from-elm/example.js' {
  declare module.exports: $Exports<'get-selection-range-from-elm/example'>;
}
declare module 'get-selection-range-from-elm/lib/index.js' {
  declare module.exports: $Exports<'get-selection-range-from-elm/lib/index'>;
}
declare module 'get-selection-range-from-elm/test.js' {
  declare module.exports: $Exports<'get-selection-range-from-elm/test'>;
}
