// flow-typed signature: 9aac723eb1fc6706b130bda2e1fb53f8
// flow-typed version: <<STUB>>/html-to-article-json_v^1.12.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-to-article-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-to-article-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-to-article-json/benchmark/node' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/index' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/normalize/flatten-tree' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/normalize/handle-whitespace' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/normalize/index' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/normalize/merge-text-nodes' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/normalize/minimum-content' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/normalize/remove-extra-linebreaks' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/parse/block-element' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/parse/embeds' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/parse/index' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/parse/text' {
  declare module.exports: any;
}

declare module 'html-to-article-json/dist/text-formattings' {
  declare module.exports: any;
}

declare module 'html-to-article-json/example/client' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/index' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/normalize/flatten-tree' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/normalize/handle-whitespace' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/normalize/index' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/normalize/merge-text-nodes' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/normalize/minimum-content' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/normalize/remove-extra-linebreaks' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/parse/block-element' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/parse/embeds' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/parse/index' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/parse/text' {
  declare module.exports: any;
}

declare module 'html-to-article-json/lib/text-formattings' {
  declare module.exports: any;
}

declare module 'html-to-article-json/test/custom-test' {
  declare module.exports: any;
}

declare module 'html-to-article-json/test/normalize-test' {
  declare module.exports: any;
}

declare module 'html-to-article-json/test/parse-figure-props-test' {
  declare module.exports: any;
}

declare module 'html-to-article-json/test/parse-normalize-test' {
  declare module.exports: any;
}

declare module 'html-to-article-json/test/parse-test' {
  declare module.exports: any;
}

declare module 'html-to-article-json/test/tape-wrapper' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-to-article-json/benchmark/node.js' {
  declare module.exports: $Exports<'html-to-article-json/benchmark/node'>;
}
declare module 'html-to-article-json/dist/index.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/index'>;
}
declare module 'html-to-article-json/dist/normalize/flatten-tree.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/normalize/flatten-tree'>;
}
declare module 'html-to-article-json/dist/normalize/handle-whitespace.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/normalize/handle-whitespace'>;
}
declare module 'html-to-article-json/dist/normalize/index.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/normalize/index'>;
}
declare module 'html-to-article-json/dist/normalize/merge-text-nodes.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/normalize/merge-text-nodes'>;
}
declare module 'html-to-article-json/dist/normalize/minimum-content.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/normalize/minimum-content'>;
}
declare module 'html-to-article-json/dist/normalize/remove-extra-linebreaks.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/normalize/remove-extra-linebreaks'>;
}
declare module 'html-to-article-json/dist/parse/block-element.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/parse/block-element'>;
}
declare module 'html-to-article-json/dist/parse/embeds.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/parse/embeds'>;
}
declare module 'html-to-article-json/dist/parse/index.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/parse/index'>;
}
declare module 'html-to-article-json/dist/parse/text.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/parse/text'>;
}
declare module 'html-to-article-json/dist/text-formattings.js' {
  declare module.exports: $Exports<'html-to-article-json/dist/text-formattings'>;
}
declare module 'html-to-article-json/example/client.js' {
  declare module.exports: $Exports<'html-to-article-json/example/client'>;
}
declare module 'html-to-article-json/lib/index.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/index'>;
}
declare module 'html-to-article-json/lib/normalize/flatten-tree.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/normalize/flatten-tree'>;
}
declare module 'html-to-article-json/lib/normalize/handle-whitespace.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/normalize/handle-whitespace'>;
}
declare module 'html-to-article-json/lib/normalize/index.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/normalize/index'>;
}
declare module 'html-to-article-json/lib/normalize/merge-text-nodes.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/normalize/merge-text-nodes'>;
}
declare module 'html-to-article-json/lib/normalize/minimum-content.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/normalize/minimum-content'>;
}
declare module 'html-to-article-json/lib/normalize/remove-extra-linebreaks.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/normalize/remove-extra-linebreaks'>;
}
declare module 'html-to-article-json/lib/parse/block-element.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/parse/block-element'>;
}
declare module 'html-to-article-json/lib/parse/embeds.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/parse/embeds'>;
}
declare module 'html-to-article-json/lib/parse/index.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/parse/index'>;
}
declare module 'html-to-article-json/lib/parse/text.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/parse/text'>;
}
declare module 'html-to-article-json/lib/text-formattings.js' {
  declare module.exports: $Exports<'html-to-article-json/lib/text-formattings'>;
}
declare module 'html-to-article-json/test/custom-test.js' {
  declare module.exports: $Exports<'html-to-article-json/test/custom-test'>;
}
declare module 'html-to-article-json/test/normalize-test.js' {
  declare module.exports: $Exports<'html-to-article-json/test/normalize-test'>;
}
declare module 'html-to-article-json/test/parse-figure-props-test.js' {
  declare module.exports: $Exports<'html-to-article-json/test/parse-figure-props-test'>;
}
declare module 'html-to-article-json/test/parse-normalize-test.js' {
  declare module.exports: $Exports<'html-to-article-json/test/parse-normalize-test'>;
}
declare module 'html-to-article-json/test/parse-test.js' {
  declare module.exports: $Exports<'html-to-article-json/test/parse-test'>;
}
declare module 'html-to-article-json/test/tape-wrapper.js' {
  declare module.exports: $Exports<'html-to-article-json/test/tape-wrapper'>;
}
