// flow-typed signature: 16f6693da53f01c984f4fddfe8475788
// flow-typed version: <<STUB>>/immutable-object-methods_v^1.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable-object-methods'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable-object-methods' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutable-object-methods/dist/assign' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/chain' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/get-in' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/index' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/map' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/merge-deep' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/set-in' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/set' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/dist/without' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/example' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/assign' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/chain' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/get-in' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/index' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/map' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/merge-deep' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/set-in' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/set' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/lib/without' {
  declare module.exports: any;
}

declare module 'immutable-object-methods/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutable-object-methods/dist/assign.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/assign'>;
}
declare module 'immutable-object-methods/dist/chain.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/chain'>;
}
declare module 'immutable-object-methods/dist/get-in.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/get-in'>;
}
declare module 'immutable-object-methods/dist/index.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/index'>;
}
declare module 'immutable-object-methods/dist/map.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/map'>;
}
declare module 'immutable-object-methods/dist/merge-deep.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/merge-deep'>;
}
declare module 'immutable-object-methods/dist/set-in.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/set-in'>;
}
declare module 'immutable-object-methods/dist/set.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/set'>;
}
declare module 'immutable-object-methods/dist/without.js' {
  declare module.exports: $Exports<'immutable-object-methods/dist/without'>;
}
declare module 'immutable-object-methods/example.js' {
  declare module.exports: $Exports<'immutable-object-methods/example'>;
}
declare module 'immutable-object-methods/lib/assign.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/assign'>;
}
declare module 'immutable-object-methods/lib/chain.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/chain'>;
}
declare module 'immutable-object-methods/lib/get-in.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/get-in'>;
}
declare module 'immutable-object-methods/lib/index.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/index'>;
}
declare module 'immutable-object-methods/lib/map.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/map'>;
}
declare module 'immutable-object-methods/lib/merge-deep.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/merge-deep'>;
}
declare module 'immutable-object-methods/lib/set-in.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/set-in'>;
}
declare module 'immutable-object-methods/lib/set.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/set'>;
}
declare module 'immutable-object-methods/lib/without.js' {
  declare module.exports: $Exports<'immutable-object-methods/lib/without'>;
}
declare module 'immutable-object-methods/test.js' {
  declare module.exports: $Exports<'immutable-object-methods/test'>;
}
