// flow-typed signature: b717b448cceffd391b64989c432bf52e
// flow-typed version: <<STUB>>/immutable-array-methods_v^1.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable-array-methods'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable-array-methods' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutable-array-methods/dist/index' {
  declare module.exports: any;
}

declare module 'immutable-array-methods/example' {
  declare module.exports: any;
}

declare module 'immutable-array-methods/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutable-array-methods/dist/index.js' {
  declare module.exports: $Exports<'immutable-array-methods/dist/index'>;
}
declare module 'immutable-array-methods/example.js' {
  declare module.exports: $Exports<'immutable-array-methods/example'>;
}
declare module 'immutable-array-methods/index' {
  declare module.exports: $Exports<'immutable-array-methods'>;
}
declare module 'immutable-array-methods/index.js' {
  declare module.exports: $Exports<'immutable-array-methods'>;
}
declare module 'immutable-array-methods/test.js' {
  declare module.exports: $Exports<'immutable-array-methods/test'>;
}
