// flow-typed signature: ccba85ad41c6aa7742efdd1764d71eb1
// flow-typed version: <<STUB>>/is-url_v^1.2.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-url/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-url/index' {
  declare module.exports: $Exports<'is-url'>;
}
declare module 'is-url/index.js' {
  declare module.exports: $Exports<'is-url'>;
}
declare module 'is-url/test/index.js' {
  declare module.exports: $Exports<'is-url/test/index'>;
}
