// flow-typed signature: 52e0b2f8ba028562bc4a9676d8906ceb
// flow-typed version: <<STUB>>/miclint_v^4.2.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'miclint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'miclint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'miclint/bin' {
  declare module.exports: any;
}

declare module 'miclint/options' {
  declare module.exports: any;
}

// Filename aliases
declare module 'miclint/bin.js' {
  declare module.exports: $Exports<'miclint/bin'>;
}
declare module 'miclint/index' {
  declare module.exports: $Exports<'miclint'>;
}
declare module 'miclint/index.js' {
  declare module.exports: $Exports<'miclint'>;
}
declare module 'miclint/options.js' {
  declare module.exports: $Exports<'miclint/options'>;
}
