// flow-typed signature: cbd480587fd780601b5c7db8febbe679
// flow-typed version: <<STUB>>/package-json-to-readme_v^2.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'package-json-to-readme'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'package-json-to-readme' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'package-json-to-readme/index' {
  declare module.exports: $Exports<'package-json-to-readme'>;
}
declare module 'package-json-to-readme/index.js' {
  declare module.exports: $Exports<'package-json-to-readme'>;
}
