// flow-typed signature: 14972e1b081079a0e001d088ea7fa59c
// flow-typed version: <<STUB>>/save-selection_v^2.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'save-selection'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'save-selection' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'save-selection/dist/index' {
  declare module.exports: any;
}

declare module 'save-selection/dist/restore' {
  declare module.exports: any;
}

declare module 'save-selection/dist/save' {
  declare module.exports: any;
}

declare module 'save-selection/example' {
  declare module.exports: any;
}

declare module 'save-selection/lib/index' {
  declare module.exports: any;
}

declare module 'save-selection/lib/restore' {
  declare module.exports: any;
}

declare module 'save-selection/lib/save' {
  declare module.exports: any;
}

declare module 'save-selection/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'save-selection/dist/index.js' {
  declare module.exports: $Exports<'save-selection/dist/index'>;
}
declare module 'save-selection/dist/restore.js' {
  declare module.exports: $Exports<'save-selection/dist/restore'>;
}
declare module 'save-selection/dist/save.js' {
  declare module.exports: $Exports<'save-selection/dist/save'>;
}
declare module 'save-selection/example.js' {
  declare module.exports: $Exports<'save-selection/example'>;
}
declare module 'save-selection/lib/index.js' {
  declare module.exports: $Exports<'save-selection/lib/index'>;
}
declare module 'save-selection/lib/restore.js' {
  declare module.exports: $Exports<'save-selection/lib/restore'>;
}
declare module 'save-selection/lib/save.js' {
  declare module.exports: $Exports<'save-selection/lib/save'>;
}
declare module 'save-selection/test.js' {
  declare module.exports: $Exports<'save-selection/test'>;
}
