// flow-typed signature: faf04c543e5cc971d1c9e0fc55c210a6
// flow-typed version: <<STUB>>/tape_v^4.5.1/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tape' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tape/example/array' {
  declare module.exports: any;
}

declare module 'tape/example/fail' {
  declare module.exports: any;
}

declare module 'tape/example/nested_fail' {
  declare module.exports: any;
}

declare module 'tape/example/nested' {
  declare module.exports: any;
}

declare module 'tape/example/not_enough' {
  declare module.exports: any;
}

declare module 'tape/example/static/server' {
  declare module.exports: any;
}

declare module 'tape/example/stream/object' {
  declare module.exports: any;
}

declare module 'tape/example/stream/tap' {
  declare module.exports: any;
}

declare module 'tape/example/stream/test/x' {
  declare module.exports: any;
}

declare module 'tape/example/stream/test/y' {
  declare module.exports: any;
}

declare module 'tape/example/throw' {
  declare module.exports: any;
}

declare module 'tape/example/timing' {
  declare module.exports: any;
}

declare module 'tape/example/too_many' {
  declare module.exports: any;
}

declare module 'tape/example/two' {
  declare module.exports: any;
}

declare module 'tape/lib/default_stream' {
  declare module.exports: any;
}

declare module 'tape/lib/results' {
  declare module.exports: any;
}

declare module 'tape/lib/test' {
  declare module.exports: any;
}

declare module 'tape/test/add-subtest-async' {
  declare module.exports: any;
}

declare module 'tape/test/array' {
  declare module.exports: any;
}

declare module 'tape/test/bound' {
  declare module.exports: any;
}

declare module 'tape/test/browser/asserts' {
  declare module.exports: any;
}

declare module 'tape/test/child_ordering' {
  declare module.exports: any;
}

declare module 'tape/test/circular-things' {
  declare module.exports: any;
}

declare module 'tape/test/comment' {
  declare module.exports: any;
}

declare module 'tape/test/deep-equal-failure' {
  declare module.exports: any;
}

declare module 'tape/test/deep' {
  declare module.exports: any;
}

declare module 'tape/test/default-messages' {
  declare module.exports: any;
}

declare module 'tape/test/double_end' {
  declare module.exports: any;
}

declare module 'tape/test/double_end/double' {
  declare module.exports: any;
}

declare module 'tape/test/end-as-callback' {
  declare module.exports: any;
}

declare module 'tape/test/exit' {
  declare module.exports: any;
}

declare module 'tape/test/exit/fail' {
  declare module.exports: any;
}

declare module 'tape/test/exit/ok' {
  declare module.exports: any;
}

declare module 'tape/test/exit/second' {
  declare module.exports: any;
}

declare module 'tape/test/exit/too_few' {
  declare module.exports: any;
}

declare module 'tape/test/exposed-harness' {
  declare module.exports: any;
}

declare module 'tape/test/fail' {
  declare module.exports: any;
}

declare module 'tape/test/many' {
  declare module.exports: any;
}

declare module 'tape/test/max_listeners' {
  declare module.exports: any;
}

declare module 'tape/test/max_listeners/source' {
  declare module.exports: any;
}

declare module 'tape/test/messages/defaults' {
  declare module.exports: any;
}

declare module 'tape/test/nested-async-plan-noend' {
  declare module.exports: any;
}

declare module 'tape/test/nested-sync-noplan-noend' {
  declare module.exports: any;
}

declare module 'tape/test/nested' {
  declare module.exports: any;
}

declare module 'tape/test/nested2' {
  declare module.exports: any;
}

declare module 'tape/test/no_callback' {
  declare module.exports: any;
}

declare module 'tape/test/onFinish' {
  declare module.exports: any;
}

declare module 'tape/test/only-twice' {
  declare module.exports: any;
}

declare module 'tape/test/only' {
  declare module.exports: any;
}

declare module 'tape/test/only2' {
  declare module.exports: any;
}

declare module 'tape/test/only3' {
  declare module.exports: any;
}

declare module 'tape/test/only4' {
  declare module.exports: any;
}

declare module 'tape/test/only5' {
  declare module.exports: any;
}

declare module 'tape/test/order' {
  declare module.exports: any;
}

declare module 'tape/test/plan_optional' {
  declare module.exports: any;
}

declare module 'tape/test/require' {
  declare module.exports: any;
}

declare module 'tape/test/require/a' {
  declare module.exports: any;
}

declare module 'tape/test/require/b' {
  declare module.exports: any;
}

declare module 'tape/test/require/test-a' {
  declare module.exports: any;
}

declare module 'tape/test/require/test-b' {
  declare module.exports: any;
}

declare module 'tape/test/skip' {
  declare module.exports: any;
}

declare module 'tape/test/stackTrace' {
  declare module.exports: any;
}

declare module 'tape/test/subcount' {
  declare module.exports: any;
}

declare module 'tape/test/subtest_and_async' {
  declare module.exports: any;
}

declare module 'tape/test/subtest_plan' {
  declare module.exports: any;
}

declare module 'tape/test/throws' {
  declare module.exports: any;
}

declare module 'tape/test/timeout' {
  declare module.exports: any;
}

declare module 'tape/test/timeoutAfter' {
  declare module.exports: any;
}

declare module 'tape/test/too_many' {
  declare module.exports: any;
}

declare module 'tape/test/undef' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tape/example/array.js' {
  declare module.exports: $Exports<'tape/example/array'>;
}
declare module 'tape/example/fail.js' {
  declare module.exports: $Exports<'tape/example/fail'>;
}
declare module 'tape/example/nested_fail.js' {
  declare module.exports: $Exports<'tape/example/nested_fail'>;
}
declare module 'tape/example/nested.js' {
  declare module.exports: $Exports<'tape/example/nested'>;
}
declare module 'tape/example/not_enough.js' {
  declare module.exports: $Exports<'tape/example/not_enough'>;
}
declare module 'tape/example/static/server.js' {
  declare module.exports: $Exports<'tape/example/static/server'>;
}
declare module 'tape/example/stream/object.js' {
  declare module.exports: $Exports<'tape/example/stream/object'>;
}
declare module 'tape/example/stream/tap.js' {
  declare module.exports: $Exports<'tape/example/stream/tap'>;
}
declare module 'tape/example/stream/test/x.js' {
  declare module.exports: $Exports<'tape/example/stream/test/x'>;
}
declare module 'tape/example/stream/test/y.js' {
  declare module.exports: $Exports<'tape/example/stream/test/y'>;
}
declare module 'tape/example/throw.js' {
  declare module.exports: $Exports<'tape/example/throw'>;
}
declare module 'tape/example/timing.js' {
  declare module.exports: $Exports<'tape/example/timing'>;
}
declare module 'tape/example/too_many.js' {
  declare module.exports: $Exports<'tape/example/too_many'>;
}
declare module 'tape/example/two.js' {
  declare module.exports: $Exports<'tape/example/two'>;
}
declare module 'tape/index' {
  declare module.exports: $Exports<'tape'>;
}
declare module 'tape/index.js' {
  declare module.exports: $Exports<'tape'>;
}
declare module 'tape/lib/default_stream.js' {
  declare module.exports: $Exports<'tape/lib/default_stream'>;
}
declare module 'tape/lib/results.js' {
  declare module.exports: $Exports<'tape/lib/results'>;
}
declare module 'tape/lib/test.js' {
  declare module.exports: $Exports<'tape/lib/test'>;
}
declare module 'tape/test/add-subtest-async.js' {
  declare module.exports: $Exports<'tape/test/add-subtest-async'>;
}
declare module 'tape/test/array.js' {
  declare module.exports: $Exports<'tape/test/array'>;
}
declare module 'tape/test/bound.js' {
  declare module.exports: $Exports<'tape/test/bound'>;
}
declare module 'tape/test/browser/asserts.js' {
  declare module.exports: $Exports<'tape/test/browser/asserts'>;
}
declare module 'tape/test/child_ordering.js' {
  declare module.exports: $Exports<'tape/test/child_ordering'>;
}
declare module 'tape/test/circular-things.js' {
  declare module.exports: $Exports<'tape/test/circular-things'>;
}
declare module 'tape/test/comment.js' {
  declare module.exports: $Exports<'tape/test/comment'>;
}
declare module 'tape/test/deep-equal-failure.js' {
  declare module.exports: $Exports<'tape/test/deep-equal-failure'>;
}
declare module 'tape/test/deep.js' {
  declare module.exports: $Exports<'tape/test/deep'>;
}
declare module 'tape/test/default-messages.js' {
  declare module.exports: $Exports<'tape/test/default-messages'>;
}
declare module 'tape/test/double_end.js' {
  declare module.exports: $Exports<'tape/test/double_end'>;
}
declare module 'tape/test/double_end/double.js' {
  declare module.exports: $Exports<'tape/test/double_end/double'>;
}
declare module 'tape/test/end-as-callback.js' {
  declare module.exports: $Exports<'tape/test/end-as-callback'>;
}
declare module 'tape/test/exit.js' {
  declare module.exports: $Exports<'tape/test/exit'>;
}
declare module 'tape/test/exit/fail.js' {
  declare module.exports: $Exports<'tape/test/exit/fail'>;
}
declare module 'tape/test/exit/ok.js' {
  declare module.exports: $Exports<'tape/test/exit/ok'>;
}
declare module 'tape/test/exit/second.js' {
  declare module.exports: $Exports<'tape/test/exit/second'>;
}
declare module 'tape/test/exit/too_few.js' {
  declare module.exports: $Exports<'tape/test/exit/too_few'>;
}
declare module 'tape/test/exposed-harness.js' {
  declare module.exports: $Exports<'tape/test/exposed-harness'>;
}
declare module 'tape/test/fail.js' {
  declare module.exports: $Exports<'tape/test/fail'>;
}
declare module 'tape/test/many.js' {
  declare module.exports: $Exports<'tape/test/many'>;
}
declare module 'tape/test/max_listeners.js' {
  declare module.exports: $Exports<'tape/test/max_listeners'>;
}
declare module 'tape/test/max_listeners/source.js' {
  declare module.exports: $Exports<'tape/test/max_listeners/source'>;
}
declare module 'tape/test/messages/defaults.js' {
  declare module.exports: $Exports<'tape/test/messages/defaults'>;
}
declare module 'tape/test/nested-async-plan-noend.js' {
  declare module.exports: $Exports<'tape/test/nested-async-plan-noend'>;
}
declare module 'tape/test/nested-sync-noplan-noend.js' {
  declare module.exports: $Exports<'tape/test/nested-sync-noplan-noend'>;
}
declare module 'tape/test/nested.js' {
  declare module.exports: $Exports<'tape/test/nested'>;
}
declare module 'tape/test/nested2.js' {
  declare module.exports: $Exports<'tape/test/nested2'>;
}
declare module 'tape/test/no_callback.js' {
  declare module.exports: $Exports<'tape/test/no_callback'>;
}
declare module 'tape/test/onFinish.js' {
  declare module.exports: $Exports<'tape/test/onFinish'>;
}
declare module 'tape/test/only-twice.js' {
  declare module.exports: $Exports<'tape/test/only-twice'>;
}
declare module 'tape/test/only.js' {
  declare module.exports: $Exports<'tape/test/only'>;
}
declare module 'tape/test/only2.js' {
  declare module.exports: $Exports<'tape/test/only2'>;
}
declare module 'tape/test/only3.js' {
  declare module.exports: $Exports<'tape/test/only3'>;
}
declare module 'tape/test/only4.js' {
  declare module.exports: $Exports<'tape/test/only4'>;
}
declare module 'tape/test/only5.js' {
  declare module.exports: $Exports<'tape/test/only5'>;
}
declare module 'tape/test/order.js' {
  declare module.exports: $Exports<'tape/test/order'>;
}
declare module 'tape/test/plan_optional.js' {
  declare module.exports: $Exports<'tape/test/plan_optional'>;
}
declare module 'tape/test/require.js' {
  declare module.exports: $Exports<'tape/test/require'>;
}
declare module 'tape/test/require/a.js' {
  declare module.exports: $Exports<'tape/test/require/a'>;
}
declare module 'tape/test/require/b.js' {
  declare module.exports: $Exports<'tape/test/require/b'>;
}
declare module 'tape/test/require/test-a.js' {
  declare module.exports: $Exports<'tape/test/require/test-a'>;
}
declare module 'tape/test/require/test-b.js' {
  declare module.exports: $Exports<'tape/test/require/test-b'>;
}
declare module 'tape/test/skip.js' {
  declare module.exports: $Exports<'tape/test/skip'>;
}
declare module 'tape/test/stackTrace.js' {
  declare module.exports: $Exports<'tape/test/stackTrace'>;
}
declare module 'tape/test/subcount.js' {
  declare module.exports: $Exports<'tape/test/subcount'>;
}
declare module 'tape/test/subtest_and_async.js' {
  declare module.exports: $Exports<'tape/test/subtest_and_async'>;
}
declare module 'tape/test/subtest_plan.js' {
  declare module.exports: $Exports<'tape/test/subtest_plan'>;
}
declare module 'tape/test/throws.js' {
  declare module.exports: $Exports<'tape/test/throws'>;
}
declare module 'tape/test/timeout.js' {
  declare module.exports: $Exports<'tape/test/timeout'>;
}
declare module 'tape/test/timeoutAfter.js' {
  declare module.exports: $Exports<'tape/test/timeoutAfter'>;
}
declare module 'tape/test/too_many.js' {
  declare module.exports: $Exports<'tape/test/too_many'>;
}
declare module 'tape/test/undef.js' {
  declare module.exports: $Exports<'tape/test/undef'>;
}
